### ISSUE TITLE
Doubt with sendPhoto and streams

### ISSUE THREAD

**Issue by alexandercerutti** [yagop/node-telegram-bot-api#267]
Hi. I have a doubt on sendPhoto method.

I have to send an image got by [plotly's `getImage()` method](https://github.com/plotly/plotly-nodejs#plotlygetimagefigure-options-callback) and its callback has as parameter a "Stream of base64 encoded imageData". If I don't use ```fs.createWriteStream()``` like in
```javascript
const filestream = fs.createWriteStream(path);
imageStream.pipe(fileStream);

console.log(fileStream); // returns a object with path property
bot.sendPhoto(toUser, fileStream);
```
I'm not able to get an object with a valid path property, so the wrapper gives me error (`Cannot read property 'toString' of undefined` on telegram.js:198:51 - `_formatSendData`). If I do that and save it in an image file, I get a delayed_stream.js error (`source.pause is not a function`). Can somebody help me to understand how can I send the image, also (if possible) without saving it? Thank you.

**Comment by GochoMugo** [comment]
The current implementation depends on the property `path` on a stream to determine the name of the file being sent. It assumes the property is **always** available, which now seems like an inconsiderate assumption.

A possible fix for this would be to fall back to a generic name, i.e. *filename*. This can be done quite easily.

However, this raises the question of whether we should allow the user to specify details of the file, in place of fall-backs or errors. For example, in cases where we can **not** detect the file-type of the contents of a buffer, we throw an error! :astonished: A better solution would be to allow the user to explicitly provide such details, in addition to fall-backs and errors.

**Comment by GochoMugo** [comment]
The error `source.pause is not a function` seems to related to *request* module **not** handling streams properly. See an almost-related issue: https://github.com/request/request/issues/1402. We will have to spend some time looking through *request*'s code and figure out the issue!

**Comment by alexandercerutti** [comment]
Well... good to know that I found a bug... or two. 😂
Coming back to the problem, I was asking for a solution and someone who would have tried to explain me the streams... I still don't know how to send a Stream via sendPhoto 😅. Anyway, thank you for the replies.

**Comment by zumoshi** [comment]
any update on this?

I've also encountered the same problem when trying to pass a stream from `ytdl-core` to `sendAudio` method. since it doesn't have the `path` property it throws an exception. both falling back to `filename` or asking for an explicit filename are acceptable solutions.

code:
```js
bot.sendAudio(msg.chat.id, ytdl.downloadFromInfo(info, {quality: 140}))
```
stack:
```
Unhandled rejection TypeError: Cannot read property 'toString' of undefined
    at TelegramBot._formatSendData (...\node_modules\node-telegram-bot-api\src\telegram.js:271:51)
    at TelegramBot.sendAudio (...\node_modules\node-telegram-bot-api\src\telegram.js:685:29)
    ...
```

**Comment by GochoMugo** [comment]
This has been fixed in **v0.30.0**.

**Comment by eisbehr-** [comment]
Using the code below, I still getting the error. Wasn't that fixed?

```JS
const stream = require('http').get('http://example.com/photo.jpg'); // use a proper URL here!
bot.sendPhoto(userId, stream);
```

> source.pause is not a function

**Comment by Fusseldieb** [comment]
Same issue as @dkern 

```
TypeError: source.pause is not a function
    at Function.DelayedStream.create (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\delayed-stream\lib\delayed_stream.js:35:12)
    at FormData.CombinedStream.append (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\combined-stream\lib\combined_stream.js:45:37)
    at FormData.append (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\form-data\lib\form_data.js:74:3)
    at appendFormValue (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\request\request.js:324:21)
    at Request.init (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\request\request.js:337:11)
    at Request.RP$initInterceptor [as init] (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\request\request.js:127:8)
    at request (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\request\index.js:53:10)
    at TelegramBot._request (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\node-telegram-bot-api\src\telegram.js:278:12)
    at TelegramBot.sendPhoto (C:\Users\Valentino\Desktop\directus\project\telegram-bot\node_modules\node-telegram-bot-api\src\telegram.js:807:17)
    at TelegramBot.onCallbackQuery (C:\Users\Valentino\Desktop\directus\project\telegram-bot\index.js:280:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
