### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by nikhiljha** [yagop/node-telegram-bot-api#89]
at C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\node-telegram-bot-api\src\telegramPolling.js:74:15
    at tryCatcher (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\nikhi\OneDrive\Documents\GitHub\RedditGram\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Unhandled rejection Error: 502 <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

**Comment by idchlife** [comment]
Quick thought - isn't it telegram server error? Is it still there?

**Comment by yagop** [comment]
Its a Telegram Server error, really annoying and most common than it should.

Try contacting them by [@BotSupport](https://telegram.me/BotSupport).

**Comment by nikhiljha** [comment]
You should probably include better error handling, right now it just spams the console with 1MB of error messages.

**Comment by idchlife** [comment]
@nikhiljha you mean that bot should recover from it without stopping? I actually can recommend you for now use pm2 with restart feature

**Comment by nikhiljha** [comment]
No, I'm saying instead of spewing out the stack trace, it should use a try catch and say something like "Telegram cloud is not responding, error 502. This issue should resolve itself shortly."

**Comment by roccomuso** [comment]
It happens often when telegram is resuming from an outage situation

**Comment by roccomuso** [comment]
That happened to me right now. And telegram was offline for a couple of hours (and apparently still having issues). There's not so much we can do.

**Comment by terrence-c** [comment]
i'm having the same error

**Comment by nikhiljha** [comment]
@Katlum As mentioned earlier in this thread, you can use pm2 to restart the bot when it crashes.

**Comment by tr91** [comment]
Whats pm2? What would be the best way to handle this error anyway? Currently my program that uses telegram would freeze indefinitely (with no prints) during that Telegram server issue, a previous version of this python-telegram-bot would raise TimedOut() errors.
